### ISSUE TITLE
gh pages のドラフト

### ISSUE THREAD

**Issue by kozo2** [PyDataOsaka/pydataosaka.github.io#1]
### 参考
https://pydata.tokyo/

### 書くこと
- [ ] twitter
- [ ] medium
- [ ] github

**Comment by bulbulpaul** [comment]
organizerのページも作るようにしたいです。

**Comment by kozo2** [comment]
#2 のように osaka.pydata.org でこのサイトにアクセス可能にする方針で行くことにしました！
のでこのissueをcloseさせていただきます！
