### ISSUE TITLE
domain

### ISSUE THREAD

**Issue by bulbulpaul** [PyDataOsaka/pydataosaka.github.io#2]
pydata osaka web pageのドメインの検討。

**Comment by bulbulpaul** [comment]
現時点で.osakaドメインはpydata空いてますね。
whoisのプロテクト含めて5000円/年ほど必要そうです。
http://domain.osaka/

**Comment by kozo2** [comment]
すみません、ドメインなのですが https://berlin.pydata.org/ のように pydata.org を pydata organization からもらえそうです。
ご検討いただきありがとうございました！
